name: validate files
on: push
jobs:
    validat-html:
        runs-on: ubuntu-latest

        steps:
            - name: pull code
              uses: actions/checkout@v4
            
            - name: validate html files if exist
              run: test -f index.html

    

