name: validate files
on: 
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    validate-index:
        runs-on: ubuntu-latest

        steps:
            - name: pull code
              uses: actions/checkout@v4
            
            - name: validate index files if exist
              run: test -f index.js

    

