name: validate files
on: push
jobs:
    validate-index:
        runs-on: ubuntu-latest

        steps:
            - name: pull code
              uses: actions/checkout@v4
            
            - name: validate index files if exist
              run: test -f index.js

    

